// Generates a throwaway `.env.test` at the repo root for the integration
// suite (docs/on-prem-deployment.md §16 Track 1.1b).
//
// Two callers:
//   • CI — `.env.test` is gitignored (it holds real local keys), so the
//     pipeline has to synthesise one before it can run integration tests.
//   • A new contributor — one command instead of hand-assembling a dozen
//     vars and running two keypair generators.
//
// Every value here is disposable and self-consistent: the JWT secret is
// random, the SAML/LTI keypairs are freshly generated, and the T-Bank
// credentials are fake (services/tbank.ts only checks its own signatures
// against them in tests — the real API is never called). Nothing in this
// file should ever be reused outside a test database.
//
// Run with: npm run test:env          (refuses to clobber an existing file)
//           npm run test:env -- --force

import { generateKeyPair, exportPKCS8, exportSPKI } from 'jose'
import { execFileSync } from 'node:child_process'
import { randomBytes, randomUUID } from 'node:crypto'
import { existsSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'

const OUT_PATH = resolve(__dirname, '../../.env.test')
const FORCE    = process.argv.includes('--force')

// Overridable so CI (or anyone with a non-default local Postgres) can point
// elsewhere. The name MUST contain "test" — both the integration globalSetup
// and setup-test-db.ts refuse to run otherwise, which is the guard that stops
// a mistyped URL from wiping a dev database.
const DATABASE_URL =
  process.env.TEST_DATABASE_URL ?? 'postgresql://postgres:postgres@localhost:5432/ispum_test'

/** PEM → single-line form with literal `\n`, the convention services/saml.ts expects. */
function inlinePem(pem: string): string {
  return pem.replace(/\r?\n/g, '\\n')
}

/**
 * Self-signed certificate for the SAML SP. node-saml wants a real certificate,
 * not a bare public key. openssl is present on GitHub runners and macOS; if it
 * somehow isn't, fall back to the SPKI public key so the file is still usable
 * for every test that doesn't parse the certificate.
 */
function selfSignedCert(privateKeyPem: string, publicKeyPem: string): string {
  const dir = mkdtempSync(join(tmpdir(), 'ispum-test-saml-'))
  try {
    const keyFile = join(dir, 'sp.key')
    const crtFile = join(dir, 'sp.crt')
    writeFileSync(keyFile, privateKeyPem, { mode: 0o600 })
    execFileSync('openssl', [
      'req', '-new', '-x509',
      '-key', keyFile,
      '-out', crtFile,
      '-days', '3650',
      '-subj', '/CN=ispum-integration-test',
    ], { stdio: 'ignore' })
    return execFileSync('cat', [crtFile], { encoding: 'utf8' })
  } catch {
    process.stderr.write('  ⚠ openssl unavailable — using the public key in place of a certificate.\n')
    return publicKeyPem
  } finally {
    rmSync(dir, { recursive: true, force: true })
  }
}

async function main(): Promise<void> {
  if (existsSync(OUT_PATH) && !FORCE) {
    console.error(
      `Refusing to overwrite ${OUT_PATH}.\n` +
      `  It may hold local keys you care about. Re-run with --force to replace it.`
    )
    process.exit(1)
  }

  const saml = await generateKeyPair('RS256', { modulusLength: 2048, extractable: true })
  const lti  = await generateKeyPair('RS256', { modulusLength: 2048, extractable: true })

  const samlPrivatePem = await exportPKCS8(saml.privateKey)
  const samlPublicPem  = await exportSPKI(saml.publicKey)
  const ltiPrivatePem  = await exportPKCS8(lti.privateKey)
  const samlCertPem    = selfSignedCert(samlPrivatePem, samlPublicPem)

  const contents = `# GENERATED by backend/scripts/generateTestEnv.ts — do not commit, do not reuse.
# Every secret below is disposable and scoped to the integration test database.

DATABASE_URL=${DATABASE_URL}
# Single connection so each test's BEGIN/ROLLBACK wraps every query it issues,
# whichever query-layer function made it (see vitest.setup.integration.ts).
DB_POOL_MAX=1
NODE_ENV=test

JWT_SECRET=${randomBytes(48).toString('hex')}
FRONTEND_URL=http://localhost:5173

# Never called in tests — the DeepSeek provider is stubbed. Present only
# because module-load-time checks expect a non-empty value.
DEEPSEEK_API_KEY=test-key-not-used

# Fake, but internally self-consistent: computeToken/verifyNotificationToken
# check signatures against these. The real T-Bank API is never contacted.
TBANK_TERMINAL_KEY=test-terminal
TBANK_TERMINAL_PASSWORD=test-password

SAML_SP_ENTITY_ID=http://localhost:3000/api/sso/sp
SAML_SP_PRIVATE_KEY="${inlinePem(samlPrivatePem)}"
SAML_SP_CERTIFICATE="${inlinePem(samlCertPem)}"

LTI_TOOL_PRIVATE_KEY="${inlinePem(ltiPrivatePem)}"
LTI_TOOL_KID="${randomUUID()}"
`

  writeFileSync(OUT_PATH, contents, { mode: 0o600 })
  console.log(`  ✓ wrote ${OUT_PATH}`)
  console.log(`    DATABASE_URL=${DATABASE_URL}`)
}

main().catch((err) => {
  console.error('Test env generation failed:', err instanceof Error ? err.message : err)
  process.exit(1)
})
