import { pool } from '../connection'
import type { Quiz, QuizQuestion, QuizLevel, PresentationSource } from '../../../../shared/types'

interface QuizRow {
  id:             string
  teacher_id:     string
  course_id:      string | null
  topic:          string
  level:          string | null
  question_count: number
  questions:      QuizQuestion[]
  sources:        PresentationSource[] | null
  created_at:     Date
}

function toQuiz(row: QuizRow): Quiz {
  return {
    id:             row.id,
    teacher_id:     row.teacher_id,
    course_id:      row.course_id,
    topic:          row.topic,
    level:          row.level as QuizLevel | null,
    question_count: row.question_count,
    questions:      row.questions,
    sources:        row.sources,
    created_at:     row.created_at.toISOString(),
  }
}

export async function createQuiz(data: {
  teacherId:     string
  courseId?:     string
  topic:         string
  level?:        QuizLevel
  questionCount: number
  questions:     QuizQuestion[]
  sources?:      PresentationSource[]
}): Promise<Quiz> {
  const { rows } = await pool.query<QuizRow>(
    `INSERT INTO quizzes
       (teacher_id, course_id, topic, level, question_count, questions, sources)
     VALUES ($1,$2,$3,$4,$5,$6,$7)
     RETURNING *`,
    [
      data.teacherId,
      data.courseId ?? null,
      data.topic,
      data.level ?? null,
      data.questionCount,
      JSON.stringify(data.questions),
      data.sources && data.sources.length > 0 ? JSON.stringify(data.sources) : null,
    ]
  )
  return toQuiz(rows[0])
}

export async function findQuizzesByTeacher(
  teacherId: string,
  courseId?: string
): Promise<Quiz[]> {
  if (courseId) {
    const { rows } = await pool.query<QuizRow>(
      `SELECT * FROM quizzes WHERE teacher_id = $1 AND course_id = $2 ORDER BY created_at DESC`,
      [teacherId, courseId]
    )
    return rows.map(toQuiz)
  }
  const { rows } = await pool.query<QuizRow>(
    'SELECT * FROM quizzes WHERE teacher_id = $1 ORDER BY created_at DESC',
    [teacherId]
  )
  return rows.map(toQuiz)
}

export async function findQuizById(id: string, teacherId: string): Promise<Quiz | null> {
  const { rows } = await pool.query<QuizRow>(
    'SELECT * FROM quizzes WHERE id = $1 AND teacher_id = $2 LIMIT 1',
    [id, teacherId]
  )
  return rows[0] ? toQuiz(rows[0]) : null
}

/** Count quizzes generated by this teacher in the current calendar month. */
export async function countQuizzesThisMonth(teacherId: string): Promise<number> {
  const { rows } = await pool.query<{ count: string }>(
    `SELECT COUNT(*)::text AS count FROM quizzes
      WHERE teacher_id = $1 AND created_at >= date_trunc('month', NOW())`,
    [teacherId]
  )
  return parseInt(rows[0].count, 10)
}

export async function deleteQuiz(id: string, teacherId: string): Promise<boolean> {
  const { rowCount } = await pool.query(
    'DELETE FROM quizzes WHERE id = $1 AND teacher_id = $2',
    [id, teacherId]
  )
  return (rowCount ?? 0) > 0
}
